/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as JcdIndexRouteImport } from './routes/jcd/index'
import { Route as UserUsernameRouteImport } from './routes/user/$username'
import { Route as AdminChar123SectionChar125RouteImport } from './routes/admin/{-$section}'
import { Route as JcdProjRouteRouteImport } from './routes/jcd/proj/route'
import { Route as JcdEnvRouteRouteImport } from './routes/jcd/env/route'
import { Route as JcdProjIndexRouteImport } from './routes/jcd/proj/index'
import { Route as JcdEnvIndexRouteImport } from './routes/jcd/env/index'
import { Route as JcdProjProjectRouteImport } from './routes/jcd/proj/$project'
import { Route as JcdEnvCopy1RouteImport } from './routes/jcd/env/copy1'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const JcdIndexRoute = JcdIndexRouteImport.update({
  id: '/jcd/',
  path: '/jcd/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUsernameRoute = UserUsernameRouteImport.update({
  id: '/user/$username',
  path: '/user/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChar123SectionChar125Route =
  AdminChar123SectionChar125RouteImport.update({
    id: '/admin/{-$section}',
    path: '/admin/{-$section}',
    getParentRoute: () => rootRouteImport,
  } as any)
const JcdProjRouteRoute = JcdProjRouteRouteImport.update({
  id: '/jcd/proj',
  path: '/jcd/proj',
  getParentRoute: () => rootRouteImport,
} as any)
const JcdEnvRouteRoute = JcdEnvRouteRouteImport.update({
  id: '/jcd/env',
  path: '/jcd/env',
  getParentRoute: () => rootRouteImport,
} as any)
const JcdProjIndexRoute = JcdProjIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JcdProjRouteRoute,
} as any)
const JcdEnvIndexRoute = JcdEnvIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JcdEnvRouteRoute,
} as any)
const JcdProjProjectRoute = JcdProjProjectRouteImport.update({
  id: '/$project',
  path: '/$project',
  getParentRoute: () => JcdProjRouteRoute,
} as any)
const JcdEnvCopy1Route = JcdEnvCopy1RouteImport.update({
  id: '/copy1',
  path: '/copy1',
  getParentRoute: () => JcdEnvRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/jcd/env': typeof JcdEnvRouteRouteWithChildren
  '/jcd/proj': typeof JcdProjRouteRouteWithChildren
  '/admin/{-$section}': typeof AdminChar123SectionChar125Route
  '/user/$username': typeof UserUsernameRoute
  '/jcd/': typeof JcdIndexRoute
  '/login/': typeof LoginIndexRoute
  '/jcd/env/copy1': typeof JcdEnvCopy1Route
  '/jcd/proj/$project': typeof JcdProjProjectRoute
  '/jcd/env/': typeof JcdEnvIndexRoute
  '/jcd/proj/': typeof JcdProjIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin/{-$section}': typeof AdminChar123SectionChar125Route
  '/user/$username': typeof UserUsernameRoute
  '/jcd': typeof JcdIndexRoute
  '/login': typeof LoginIndexRoute
  '/jcd/env/copy1': typeof JcdEnvCopy1Route
  '/jcd/proj/$project': typeof JcdProjProjectRoute
  '/jcd/env': typeof JcdEnvIndexRoute
  '/jcd/proj': typeof JcdProjIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/jcd/env': typeof JcdEnvRouteRouteWithChildren
  '/jcd/proj': typeof JcdProjRouteRouteWithChildren
  '/admin/{-$section}': typeof AdminChar123SectionChar125Route
  '/user/$username': typeof UserUsernameRoute
  '/jcd/': typeof JcdIndexRoute
  '/login/': typeof LoginIndexRoute
  '/jcd/env/copy1': typeof JcdEnvCopy1Route
  '/jcd/proj/$project': typeof JcdProjProjectRoute
  '/jcd/env/': typeof JcdEnvIndexRoute
  '/jcd/proj/': typeof JcdProjIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/jcd/env'
    | '/jcd/proj'
    | '/admin/{-$section}'
    | '/user/$username'
    | '/jcd/'
    | '/login/'
    | '/jcd/env/copy1'
    | '/jcd/proj/$project'
    | '/jcd/env/'
    | '/jcd/proj/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin/{-$section}'
    | '/user/$username'
    | '/jcd'
    | '/login'
    | '/jcd/env/copy1'
    | '/jcd/proj/$project'
    | '/jcd/env'
    | '/jcd/proj'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/jcd/env'
    | '/jcd/proj'
    | '/admin/{-$section}'
    | '/user/$username'
    | '/jcd/'
    | '/login/'
    | '/jcd/env/copy1'
    | '/jcd/proj/$project'
    | '/jcd/env/'
    | '/jcd/proj/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  JcdEnvRouteRoute: typeof JcdEnvRouteRouteWithChildren
  JcdProjRouteRoute: typeof JcdProjRouteRouteWithChildren
  AdminChar123SectionChar125Route: typeof AdminChar123SectionChar125Route
  UserUsernameRoute: typeof UserUsernameRoute
  JcdIndexRoute: typeof JcdIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jcd/': {
      id: '/jcd/'
      path: '/jcd'
      fullPath: '/jcd/'
      preLoaderRoute: typeof JcdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$username': {
      id: '/user/$username'
      path: '/user/$username'
      fullPath: '/user/$username'
      preLoaderRoute: typeof UserUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/{-$section}': {
      id: '/admin/{-$section}'
      path: '/admin/{-$section}'
      fullPath: '/admin/{-$section}'
      preLoaderRoute: typeof AdminChar123SectionChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jcd/proj': {
      id: '/jcd/proj'
      path: '/jcd/proj'
      fullPath: '/jcd/proj'
      preLoaderRoute: typeof JcdProjRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jcd/env': {
      id: '/jcd/env'
      path: '/jcd/env'
      fullPath: '/jcd/env'
      preLoaderRoute: typeof JcdEnvRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jcd/proj/': {
      id: '/jcd/proj/'
      path: '/'
      fullPath: '/jcd/proj/'
      preLoaderRoute: typeof JcdProjIndexRouteImport
      parentRoute: typeof JcdProjRouteRoute
    }
    '/jcd/env/': {
      id: '/jcd/env/'
      path: '/'
      fullPath: '/jcd/env/'
      preLoaderRoute: typeof JcdEnvIndexRouteImport
      parentRoute: typeof JcdEnvRouteRoute
    }
    '/jcd/proj/$project': {
      id: '/jcd/proj/$project'
      path: '/$project'
      fullPath: '/jcd/proj/$project'
      preLoaderRoute: typeof JcdProjProjectRouteImport
      parentRoute: typeof JcdProjRouteRoute
    }
    '/jcd/env/copy1': {
      id: '/jcd/env/copy1'
      path: '/copy1'
      fullPath: '/jcd/env/copy1'
      preLoaderRoute: typeof JcdEnvCopy1RouteImport
      parentRoute: typeof JcdEnvRouteRoute
    }
  }
}

interface JcdEnvRouteRouteChildren {
  JcdEnvCopy1Route: typeof JcdEnvCopy1Route
  JcdEnvIndexRoute: typeof JcdEnvIndexRoute
}

const JcdEnvRouteRouteChildren: JcdEnvRouteRouteChildren = {
  JcdEnvCopy1Route: JcdEnvCopy1Route,
  JcdEnvIndexRoute: JcdEnvIndexRoute,
}

const JcdEnvRouteRouteWithChildren = JcdEnvRouteRoute._addFileChildren(
  JcdEnvRouteRouteChildren,
)

interface JcdProjRouteRouteChildren {
  JcdProjProjectRoute: typeof JcdProjProjectRoute
  JcdProjIndexRoute: typeof JcdProjIndexRoute
}

const JcdProjRouteRouteChildren: JcdProjRouteRouteChildren = {
  JcdProjProjectRoute: JcdProjProjectRoute,
  JcdProjIndexRoute: JcdProjIndexRoute,
}

const JcdProjRouteRouteWithChildren = JcdProjRouteRoute._addFileChildren(
  JcdProjRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  JcdEnvRouteRoute: JcdEnvRouteRouteWithChildren,
  JcdProjRouteRoute: JcdProjRouteRouteWithChildren,
  AdminChar123SectionChar125Route: AdminChar123SectionChar125Route,
  UserUsernameRoute: UserUsernameRoute,
  JcdIndexRoute: JcdIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
