/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as JcdIndexRouteImport } from './routes/jcd/index'
import { Route as UserUsernameRouteImport } from './routes/user/$username'
import { Route as JcdProjectRouteImport } from './routes/jcd/$project'
import { Route as AdminChar123SectionChar125RouteImport } from './routes/admin/{-$section}'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const JcdIndexRoute = JcdIndexRouteImport.update({
  id: '/jcd/',
  path: '/jcd/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUsernameRoute = UserUsernameRouteImport.update({
  id: '/user/$username',
  path: '/user/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const JcdProjectRoute = JcdProjectRouteImport.update({
  id: '/jcd/$project',
  path: '/jcd/$project',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChar123SectionChar125Route =
  AdminChar123SectionChar125RouteImport.update({
    id: '/admin/{-$section}',
    path: '/admin/{-$section}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin/{-$section}': typeof AdminChar123SectionChar125Route
  '/jcd/$project': typeof JcdProjectRoute
  '/user/$username': typeof UserUsernameRoute
  '/jcd/': typeof JcdIndexRoute
  '/login/': typeof LoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin/{-$section}': typeof AdminChar123SectionChar125Route
  '/jcd/$project': typeof JcdProjectRoute
  '/user/$username': typeof UserUsernameRoute
  '/jcd': typeof JcdIndexRoute
  '/login': typeof LoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin/{-$section}': typeof AdminChar123SectionChar125Route
  '/jcd/$project': typeof JcdProjectRoute
  '/user/$username': typeof UserUsernameRoute
  '/jcd/': typeof JcdIndexRoute
  '/login/': typeof LoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin/{-$section}'
    | '/jcd/$project'
    | '/user/$username'
    | '/jcd/'
    | '/login/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin/{-$section}'
    | '/jcd/$project'
    | '/user/$username'
    | '/jcd'
    | '/login'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin/{-$section}'
    | '/jcd/$project'
    | '/user/$username'
    | '/jcd/'
    | '/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminChar123SectionChar125Route: typeof AdminChar123SectionChar125Route
  JcdProjectRoute: typeof JcdProjectRoute
  UserUsernameRoute: typeof UserUsernameRoute
  JcdIndexRoute: typeof JcdIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jcd/': {
      id: '/jcd/'
      path: '/jcd'
      fullPath: '/jcd/'
      preLoaderRoute: typeof JcdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$username': {
      id: '/user/$username'
      path: '/user/$username'
      fullPath: '/user/$username'
      preLoaderRoute: typeof UserUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jcd/$project': {
      id: '/jcd/$project'
      path: '/jcd/$project'
      fullPath: '/jcd/$project'
      preLoaderRoute: typeof JcdProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/{-$section}': {
      id: '/admin/{-$section}'
      path: '/admin/{-$section}'
      fullPath: '/admin/{-$section}'
      preLoaderRoute: typeof AdminChar123SectionChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminChar123SectionChar125Route: AdminChar123SectionChar125Route,
  JcdProjectRoute: JcdProjectRoute,
  UserUsernameRoute: UserUsernameRoute,
  JcdIndexRoute: JcdIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
