/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as JcdIndexRouteImport } from './routes/jcd/index'
import { Route as UserUsernameRouteImport } from './routes/user/$username'
import { Route as AdminChar123SectionChar125RouteImport } from './routes/admin/{-$section}'
import { Route as JcdProjIndexRouteImport } from './routes/jcd/proj/index'
import { Route as JcdNsIndexRouteImport } from './routes/jcd/ns/index'
import { Route as JcdProjProjectRouteImport } from './routes/jcd/proj/$project'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const JcdIndexRoute = JcdIndexRouteImport.update({
  id: '/jcd/',
  path: '/jcd/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUsernameRoute = UserUsernameRouteImport.update({
  id: '/user/$username',
  path: '/user/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChar123SectionChar125Route =
  AdminChar123SectionChar125RouteImport.update({
    id: '/admin/{-$section}',
    path: '/admin/{-$section}',
    getParentRoute: () => rootRouteImport,
  } as any)
const JcdProjIndexRoute = JcdProjIndexRouteImport.update({
  id: '/jcd/proj/',
  path: '/jcd/proj/',
  getParentRoute: () => rootRouteImport,
} as any)
const JcdNsIndexRoute = JcdNsIndexRouteImport.update({
  id: '/jcd/ns/',
  path: '/jcd/ns/',
  getParentRoute: () => rootRouteImport,
} as any)
const JcdProjProjectRoute = JcdProjProjectRouteImport.update({
  id: '/jcd/proj/$project',
  path: '/jcd/proj/$project',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin/{-$section}': typeof AdminChar123SectionChar125Route
  '/user/$username': typeof UserUsernameRoute
  '/jcd/': typeof JcdIndexRoute
  '/login/': typeof LoginIndexRoute
  '/jcd/proj/$project': typeof JcdProjProjectRoute
  '/jcd/ns/': typeof JcdNsIndexRoute
  '/jcd/proj/': typeof JcdProjIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin/{-$section}': typeof AdminChar123SectionChar125Route
  '/user/$username': typeof UserUsernameRoute
  '/jcd': typeof JcdIndexRoute
  '/login': typeof LoginIndexRoute
  '/jcd/proj/$project': typeof JcdProjProjectRoute
  '/jcd/ns': typeof JcdNsIndexRoute
  '/jcd/proj': typeof JcdProjIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin/{-$section}': typeof AdminChar123SectionChar125Route
  '/user/$username': typeof UserUsernameRoute
  '/jcd/': typeof JcdIndexRoute
  '/login/': typeof LoginIndexRoute
  '/jcd/proj/$project': typeof JcdProjProjectRoute
  '/jcd/ns/': typeof JcdNsIndexRoute
  '/jcd/proj/': typeof JcdProjIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin/{-$section}'
    | '/user/$username'
    | '/jcd/'
    | '/login/'
    | '/jcd/proj/$project'
    | '/jcd/ns/'
    | '/jcd/proj/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin/{-$section}'
    | '/user/$username'
    | '/jcd'
    | '/login'
    | '/jcd/proj/$project'
    | '/jcd/ns'
    | '/jcd/proj'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin/{-$section}'
    | '/user/$username'
    | '/jcd/'
    | '/login/'
    | '/jcd/proj/$project'
    | '/jcd/ns/'
    | '/jcd/proj/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminChar123SectionChar125Route: typeof AdminChar123SectionChar125Route
  UserUsernameRoute: typeof UserUsernameRoute
  JcdIndexRoute: typeof JcdIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  JcdProjProjectRoute: typeof JcdProjProjectRoute
  JcdNsIndexRoute: typeof JcdNsIndexRoute
  JcdProjIndexRoute: typeof JcdProjIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jcd/': {
      id: '/jcd/'
      path: '/jcd'
      fullPath: '/jcd/'
      preLoaderRoute: typeof JcdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$username': {
      id: '/user/$username'
      path: '/user/$username'
      fullPath: '/user/$username'
      preLoaderRoute: typeof UserUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/{-$section}': {
      id: '/admin/{-$section}'
      path: '/admin/{-$section}'
      fullPath: '/admin/{-$section}'
      preLoaderRoute: typeof AdminChar123SectionChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jcd/proj/': {
      id: '/jcd/proj/'
      path: '/jcd/proj'
      fullPath: '/jcd/proj/'
      preLoaderRoute: typeof JcdProjIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jcd/ns/': {
      id: '/jcd/ns/'
      path: '/jcd/ns'
      fullPath: '/jcd/ns/'
      preLoaderRoute: typeof JcdNsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jcd/proj/$project': {
      id: '/jcd/proj/$project'
      path: '/jcd/proj/$project'
      fullPath: '/jcd/proj/$project'
      preLoaderRoute: typeof JcdProjProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminChar123SectionChar125Route: AdminChar123SectionChar125Route,
  UserUsernameRoute: UserUsernameRoute,
  JcdIndexRoute: JcdIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  JcdProjProjectRoute: JcdProjProjectRoute,
  JcdNsIndexRoute: JcdNsIndexRoute,
  JcdProjIndexRoute: JcdProjIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
